<a href="https://colab.research.google.com/github/Moksh45/PyTorch-for-deep-learning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##PyTorch Fundamentals

In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


#Introduction To Tensors

### Creating tensors


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python list
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
Matrix = torch.tensor([[7,7],[4,5]])
Matrix

tensor([[7, 7],
        [4, 5]])

In [11]:
Matrix.ndim

2

In [12]:
Matrix[0][1]

tensor(7)

In [13]:
Matrix.shape

torch.Size([2, 2])

In [14]:
# Tensor 
Tensor = torch.tensor([[[1,2,3,],[4,5,6],[7,8,9]]])

In [15]:
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
Tensor.ndim

3

In [17]:
Tensor.shape

torch.Size([1, 3, 3])

## Random Tensors

##### Why Random Trnsors?
Random tensors are important because the way many neural networks learn is that they start with tensor full of random number and adjust those random number to better represent the data.

`Start with random number -> look at data -> update random number -> look at data -> update random number`

In [18]:
#create a random Tensor of sixe (3,4)
random_tensor = torch.rand(1,3,10)
random_tensor

tensor([[[0.9097, 0.9010, 0.5550, 0.3704, 0.0876, 0.7535, 0.3369, 0.0853,
          0.3626, 0.2066],
         [0.6243, 0.1699, 0.5826, 0.7754, 0.5205, 0.2265, 0.4177, 0.4430,
          0.0296, 0.8172],
         [0.0031, 0.0280, 0.1333, 0.9979, 0.3368, 0.2569, 0.6388, 0.6550,
          0.8758, 0.8064]]])

In [19]:
random_tensor.ndim

3

In [20]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))  # height, Width, colour channel
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [21]:
#Create a tensor of all Zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

#Creating a range of tensors and tensors-like

In [28]:
# Use Torch.range()
a=torch.range(0,10)
print(a)
print(a.dtype)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
torch.float32


<ipython-input-28-2574e71674bb>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a=torch.range(0,10)


In [29]:
a=torch.arange(0,10)
print(a)
print(a.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


In [36]:
a1=torch.arange(start = 0,end = 1000, step = 77)
print(a1)
print(a1.dtype)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
torch.int64


#Creating a range of tensors and tensors-like

In [37]:
ten_zeros = torch.zeros_like(input = a1)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])