<a href="https://colab.research.google.com/github/Moksh45/PyTorch-for-deep-learning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##PyTorch Fundamentals

In [2]:
print("Hello")

Hello


In [3]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


#Introduction To Tensors

### Creating tensors


In [5]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python list
scalar.item()

7

In [8]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#matrix
Matrix = torch.tensor([[7,7],[4,5]])
Matrix

tensor([[7, 7],
        [4, 5]])

In [12]:
Matrix.ndim

2

In [14]:
Matrix[0][1]

tensor(7)

In [15]:
Matrix.shape

torch.Size([2, 2])

In [16]:
# Tensor 
Tensor = torch.tensor([[[1,2,3,],[4,5,6],[7,8,9]]])

In [17]:
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
Tensor.ndim

3

In [20]:
Tensor.shape

torch.Size([1, 3, 3])