<a href="https://colab.research.google.com/github/Moksh45/PyTorch-for-deep-learning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##PyTorch Fundamentals

In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


#Introduction To Tensors

### Creating tensors


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python list
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
Matrix = torch.tensor([[7,7],[4,5]])
Matrix

tensor([[7, 7],
        [4, 5]])

In [11]:
Matrix.ndim

2

In [12]:
Matrix[0][1]

tensor(7)

In [13]:
Matrix.shape

torch.Size([2, 2])

In [14]:
# Tensor 
Tensor = torch.tensor([[[1,2,3,],[4,5,6],[7,8,9]]])

In [15]:
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
Tensor.ndim

3

In [17]:
Tensor.shape

torch.Size([1, 3, 3])

## Random Tensors

##### Why Random Trnsors?
Random tensors are important because the way many neural networks learn is that they start with tensor full of random number and adjust those random number to better represent the data.

`Start with random number -> look at data -> update random number -> look at data -> update random number`

In [18]:
#create a random Tensor of sixe (3,4)
random_tensor = torch.rand(1,3,10)
random_tensor

tensor([[[0.2454, 0.7971, 0.4601, 0.5729, 0.1322, 0.6067, 0.7620, 0.4768,
          0.1868, 0.3450],
         [0.8270, 0.3403, 0.8759, 0.2920, 0.2759, 0.1065, 0.5848, 0.0599,
          0.7383, 0.3703],
         [0.0403, 0.6238, 0.3989, 0.0474, 0.7288, 0.6542, 0.4828, 0.0254,
          0.2989, 0.4563]]])

In [19]:
random_tensor.ndim

3

In [20]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))  # height, Width, colour channel
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [21]:
#Create a tensor of all Zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

#Creating a range of tensors and tensors-like

In [24]:
# Use Torch.range()
a=torch.range(0,10)
print(a)
print(a.dtype)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
torch.float32


<ipython-input-24-2574e71674bb>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a=torch.range(0,10)


In [25]:
a=torch.arange(0,10)
print(a)
print(a.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


In [26]:
a1=torch.arange(start = 0,end = 1000, step = 77)
print(a1)
print(a1.dtype)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
torch.int64


#Creating a range of tensors and tensors-like

In [27]:
ten_zeros = torch.zeros_like(input = a1)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatype

**Note:** Tensor datatype is one of the 3 big error you'll run into with PyTorch & deep learning

1. Tensaor not right datatyoe
2. Tensors not Right shape
3. Tensor not on the right device 

In [28]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,  #What datatype is the tensor (Eg. float32 or float16)
                               device=None, #What device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors oprations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)   #convert Datatype or change datatype of tensor

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

## **Getting information from tensors** (Tensor attribute)

1. Tensaor not right datatype - to do get datatpye from a tensor, can use tensor,dtype
2. Tensors not Right shape - to get shape from a tensor can use tensor.shape
3. Tensor not on the right device - to get device from a tensor, can use tensor.device 






In [34]:
 #create a tensor
 some_tensor = torch.rand(4,5)
 some_tensor

tensor([[0.3100, 0.1667, 0.9772, 0.5859, 0.5735],
        [0.1159, 0.4143, 0.1232, 0.9771, 0.3717],
        [0.6595, 0.2704, 0.5625, 0.1230, 0.9508],
        [0.6839, 0.8154, 0.5740, 0.0336, 0.9252]])

In [36]:
#Find ou detail about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Shape of tensor : {some_tensor.device}")

tensor([[0.3100, 0.1667, 0.9772, 0.5859, 0.5735],
        [0.1159, 0.4143, 0.1232, 0.9771, 0.3717],
        [0.6595, 0.2704, 0.5625, 0.1230, 0.9508],
        [0.6839, 0.8154, 0.5740, 0.0336, 0.9252]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([4, 5])
Shape of tensor : cpu


### Mainpulating Tensor (Tensor operations)

Tensor operations include :
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [37]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# create a tensor and subtraction 10 to it
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [39]:
# create a tensor and MUL 10 to it
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [40]:
# create a tensor and division 10 to it
tensor = torch.tensor([1,2,3])
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [42]:
# try out PyTorch in-built Function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix Multiplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisy:

1.the **inner dimension** must match:

* `(3,2) @ (3,2)`won't work 

* `(2,3) @ (3,2)`Will work

* `(3,2) @ (2,3)`will work 

In [47]:
# Element-wise multiplication
print(tensor ,"*" , tensor)
print("Equals : ",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :  tensor([1, 4, 9])


In [49]:
#Matrix Multiplication
%%time
torch.matmul(tensor,tensor) #you can use this or 

CPU times: user 208 µs, sys: 0 ns, total: 208 µs
Wall time: 214 µs


tensor(14)

In [51]:
#or use this for matrix multiplication
tensor @ tensor

tensor(14)