<a href="https://colab.research.google.com/github/Moksh45/PyTorch-for-deep-learning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##PyTorch Fundamentals

In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


#Introduction To Tensors

### Creating tensors


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python list
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
Matrix = torch.tensor([[7,7],[4,5]])
Matrix

tensor([[7, 7],
        [4, 5]])

In [11]:
Matrix.ndim

2

In [12]:
Matrix[0][1]

tensor(7)

In [13]:
Matrix.shape

torch.Size([2, 2])

In [14]:
# Tensor 
Tensor = torch.tensor([[[1,2,3,],[4,5,6],[7,8,9]]])

In [15]:
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
Tensor.ndim

3

In [17]:
Tensor.shape

torch.Size([1, 3, 3])

## Random Tensors

##### Why Random Trnsors?
Random tensors are important because the way many neural networks learn is that they start with tensor full of random number and adjust those random number to better represent the data.

`Start with random number -> look at data -> update random number -> look at data -> update random number`

In [18]:
#create a random Tensor of sixe (3,4)
random_tensor = torch.rand(1,3,10)
random_tensor

tensor([[[0.4468, 0.4603, 0.3318, 0.3114, 0.0031, 0.8280, 0.4529, 0.4534,
          0.7297, 0.0158],
         [0.8594, 0.5972, 0.7419, 0.3351, 0.7396, 0.0110, 0.1791, 0.3758,
          0.4028, 0.9057],
         [0.2661, 0.7916, 0.9300, 0.5113, 0.6743, 0.9240, 0.7052, 0.8107,
          0.4060, 0.0665]]])

In [19]:
random_tensor.ndim

3

In [20]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))  # height, Width, colour channel
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [21]:
#Create a tensor of all Zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

#Creating a range of tensors and tensors-like

In [24]:
# Use Torch.range()
a=torch.range(0,10)
print(a)
print(a.dtype)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
torch.float32


<ipython-input-24-2574e71674bb>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a=torch.range(0,10)


In [25]:
a=torch.arange(0,10)
print(a)
print(a.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


In [26]:
a1=torch.arange(start = 0,end = 1000, step = 77)
print(a1)
print(a1.dtype)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
torch.int64


#Creating a range of tensors and tensors-like

In [27]:
ten_zeros = torch.zeros_like(input = a1)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatype

**Note:** Tensor datatype is one of the 3 big error you'll run into with PyTorch & deep learning

1. Tensaor not right datatyoe
2. Tensors not Right shape
3. Tensor not on the right device 

In [28]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,  #What datatype is the tensor (Eg. float32 or float16)
                               device=None, #What device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors oprations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)   #convert Datatype or change datatype of tensor

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

## **Getting information from tensors** (Tensor attribute)

1. Tensaor not right datatype - to do get datatpye from a tensor, can use tensor,dtype
2. Tensors not Right shape - to get shape from a tensor can use tensor.shape
3. Tensor not on the right device - to get device from a tensor, can use tensor.device 






In [34]:
 #create a tensor
 some_tensor = torch.rand(4,5)
 some_tensor

tensor([[0.5341, 0.3250, 0.7977, 0.2284, 0.9122],
        [0.8317, 0.9338, 0.6521, 0.5266, 0.1870],
        [0.7306, 0.5847, 0.0330, 0.1088, 0.7232],
        [0.3783, 0.1293, 0.7746, 0.4439, 0.5331]])

In [35]:
#Find ou detail about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Shape of tensor : {some_tensor.device}")

tensor([[0.5341, 0.3250, 0.7977, 0.2284, 0.9122],
        [0.8317, 0.9338, 0.6521, 0.5266, 0.1870],
        [0.7306, 0.5847, 0.0330, 0.1088, 0.7232],
        [0.3783, 0.1293, 0.7746, 0.4439, 0.5331]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([4, 5])
Shape of tensor : cpu


### Mainpulating Tensor (Tensor operations)

Tensor operations include :
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [36]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# create a tensor and subtraction 10 to it
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [38]:
# create a tensor and MUL 10 to it
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [39]:
# create a tensor and division 10 to it
tensor = torch.tensor([1,2,3])
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [40]:
# try out PyTorch in-built Function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix Multiplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisy:

1.the **inner dimension** must match:

* `(3,2) @ (3,2)`won't work 

* `(2,3) @ (3,2)`Will work

* `(3,2) @ (2,3)`will work

2. The resulting Matrix has the shape of the **Outer dimensions**:

* `(2, 3) @ (3, 2)` -> `(2, 2)`

* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [42]:
# Element-wise multiplication
print(tensor ,"*" , tensor)
print("Equals : ",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :  tensor([1, 4, 9])


In [43]:
#Matrix Multiplication
%%time
torch.matmul(tensor,tensor) #you can use this or 

CPU times: user 2.97 ms, sys: 0 ns, total: 2.97 ms
Wall time: 3.21 ms


tensor(14)

In [44]:
#or use this for matrix multiplication
tensor @ tensor

tensor(14)

#One of the most common error in deep learning: shape error

In [45]:
#shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,9],
                         [9,12]])
#torch.mm(tensor_A,tensor_B) ## tourch.mm is the same as touch.matmul 

To fix our tensor shape issuse, we can manipulate the shape of one of our tensor using a torch.transpose

A **transpose** switches the axes or dimension of a given tensor.

In [46]:
tensor_B.T   #T stand for transpose   

tensor([[ 7,  8,  9],
        [10,  9, 12]])

In [47]:
tensor_B.T.shape

torch.Size([2, 3])

In [48]:
torch.mm(tensor_A,tensor_B.T) ,torch.mm(tensor_A,tensor_B.T).shape

(tensor([[ 27,  26,  33],
         [ 61,  60,  75],
         [ 95,  94, 117]]), torch.Size([3, 3]))

## **Finding the min.max.mean,sum.etc (Tensor aggregation)**

In [49]:
#create a tensor 
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [50]:
#find the min 
torch.min(x) ,x.min()

(tensor(1), tensor(1))

In [51]:
#find the max
torch.max(x) ,x.max()

(tensor(91), tensor(91))

In [52]:
#find the mean  - note : the torch.mean() function requires a tensor of float32
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [53]:
#find the sum 
torch.sum(x) ,x.sum()

(tensor(460), tensor(460))

###Finding the Positional min and max

In [54]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [55]:
# Find the position in tensor that has the minimum value with argmin( -> returns index position of target tensor where thr minimum value occurs  ) 
x.argmin()

tensor(0)

In [56]:
x.argmax()

tensor(9)

## Reshaping , stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combind multiple tensor on top of each other (vstack) or side by side (hstack)
* squeeze - removes all `1` dimensions from a tensor  
* unsqueeze - add all `1` dimensions to a target tensor
* permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [57]:
#let's create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
#add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [59]:
# change the view 
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z changes x (Because a view of a tensor shares the same memory as the original input)
z[:,0] =5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
# Stack tensor on top each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
# torch.squeeze () - removes all single dimension from a target tensor
x_reshaped = x.reshape(1,9)
print(f"Previous Tensor : {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

Previous Tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])


In [63]:
x_reshaped.squeeze()  #squeeze change it into 1 dimension

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
x_squeezed = x_reshaped.squeeze()
print(f" New Tensor : {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")

 New Tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


In [65]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous Tensor : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\n New Tensor : {x_unsqueezed}")
print(f"Previous shape : {x_unsqueezed.shape}")



Previous Tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

 New Tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])


In [69]:
#torch.permute - rearrange the dimension of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3))  #[height, width, colur_channels]

#Permute the original tensor to rearrange the axis (or dim)
x_permuted = x_original.permute(2,0,1) #shift axis 0->1, 1->2, 2->0
print(f"Previous Tensor : {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")  #[colour_channel, height, width]



Previous Tensor : torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [74]:
x_permuted

tensor([[[0.3778, 0.7802, 0.9524,  ..., 0.3726, 0.0893, 0.2420],
         [0.9956, 0.7764, 0.2625,  ..., 0.5614, 0.2650, 0.4545],
         [0.2595, 0.2745, 0.1019,  ..., 0.3704, 0.8232, 0.1144],
         ...,
         [0.1880, 0.6896, 0.0700,  ..., 0.4834, 0.1561, 0.3865],
         [0.4331, 0.1976, 0.4466,  ..., 0.0035, 0.1975, 0.5180],
         [0.1233, 0.3661, 0.3636,  ..., 0.1514, 0.3313, 0.6923]],

        [[0.8100, 0.7467, 0.1199,  ..., 0.3513, 0.2641, 0.9064],
         [0.6406, 0.6210, 0.5155,  ..., 0.3113, 0.6457, 0.8931],
         [0.1951, 0.8140, 0.4811,  ..., 0.9545, 0.8287, 0.1841],
         ...,
         [0.9517, 0.4879, 0.5363,  ..., 0.0708, 0.9794, 0.8578],
         [0.5681, 0.7649, 0.3617,  ..., 0.2261, 0.7801, 0.1758],
         [0.1562, 0.1506, 0.1285,  ..., 0.6155, 0.1691, 0.2632]],

        [[0.2736, 0.1136, 0.4140,  ..., 0.5681, 0.0397, 0.1718],
         [0.2220, 0.3521, 0.3920,  ..., 0.7074, 0.6154, 0.4971],
         [0.3378, 0.4688, 0.0363,  ..., 0.6316, 0.2327, 0.

# Indexing (selecting data from Tensors)

indexing with PyTorch is similar to indexing with Numpy

In [90]:
x=torch.arange(1,13).reshape(1,3,4)
x

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [94]:
#indexing
x[0][2][0]

tensor(9)

In [96]:
# You can also use ":" to select "all" of a target dimension
x[:,1]

tensor([[5, 6, 7, 8]])

In [98]:
# Get all values of 0th and last dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[ 2,  6, 10]])

In [99]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([6])

In [100]:
x[:,:,3]

tensor([[ 4,  8, 12]])

#PyTorch tensors & Numpy

## Numpy is a popular scientific python numercial computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, Want in Pytorch -> `torch.from_numpy(ndarray)`

* PyTorch tensor -> Numpy ->`torch.Tensor.numpy()`

In [102]:
import numpy as np

In [113]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)  #warning: when converting from numpy -> pytorch, Pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [114]:
#Change the value of array, what will this do to `Tensor`?
array = array +1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [119]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [120]:
#Change the value of tensor, what happes to `numpy_tensor`?

tensor = tensor +1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))